package world.wholestory.api.shared.domain;

import java.util.Objects;
import java.util.UUID;

/** Identity of a user. Time-ordered (UUIDv7) and generated by the application, never by the database (D-040). */
public record UserId(UUID value) {

    public UserId {
        Objects.requireNonNull(value, "a user id is required");
    }

    public static UserId of(UUID value) {
        return new UserId(value);
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
